# Generated by Django 6.0.1 on 2026-03-02 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_eventmaster_capacity_eventmaster_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmaster',
            name='bg_color',
            field=models.TextField(blank=True, null=True),
        ),
    ]
