# Generated by Django 6.0.1 on 2026-03-02 13:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_eventmaster_bg_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmaster',
            name='google_maps_address',
            field=models.TextField(blank=True, default='', help_text='Full address for Google Maps integration'),
        ),
        migrations.AddField(
            model_name='eventmaster',
            name='highlights',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventmaster',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='eventmaster',
            name='location',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventmaster',
            name='location_link',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventmaster',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.CreateModel(
            name='EventTag',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Event Tag',
                'verbose_name_plural': 'Event Tags',
            },
        ),
        migrations.AddField(
            model_name='eventmaster',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='events', to='db.eventtag'),
        ),
    ]
