# Generated by Django 6.0.1 on 2026-03-02 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_eventmaster_google_maps_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventcategory',
            name='emoji',
            field=models.CharField(blank=True, default='🎵', max_length=10, null=True),
        ),
    ]
