# Generated by Django 6.0.1 on 2026-03-03 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0007_asset_eventmaster_main_image_eventasset_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventmaster',
            name='organizer',
        ),
        migrations.RemoveField(
            model_name='eventmaster',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='eventmaster',
            name='google_maps_address',
        ),
        migrations.RemoveField(
            model_name='eventmaster',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='eventmaster',
            name='location',
        ),
        migrations.RemoveField(
            model_name='eventmaster',
            name='location_link',
        ),
        migrations.RemoveField(
            model_name='eventmaster',
            name='longitude',
        ),
        migrations.AddField(
            model_name='eventmaster',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eventticket',
            name='cover_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_ticket_cover_images', to='db.asset'),
        ),
        migrations.AlterField(
            model_name='eventticket',
            name='price_type',
            field=models.CharField(choices=[('FREE', 'Free'), ('PAID', 'Paid')], default='PAID', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='eventticket',
            unique_together={('event', 'name')},
        ),
        migrations.DeleteModel(
            name='EventOrganizer',
        ),
    ]
