# Generated by Django 6.0.1 on 2026-03-04 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0008_remove_eventmaster_organizer_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='eventmaster',
            index=models.Index(fields=['start_at', 'is_published', 'end_at', 'is_featured'], name='db_eventmas_start_a_7a3044_idx'),
        ),
    ]
